In [1]:
import pandas as pd

data = {
    "Name": ["A","B","C","D","E","F","G","H","I","J"],
    "Sex": ["F","M","F","F","M","M","F","M","F","M"],
    "Pclass": [1,3,3,1,3,2,2,3,1,2],
    "Age": [38,22,26,35,35,28,19,40,30,25],
    "Fare": [71,7,8,53,8,13,26,7,80,15],
    "Survived": [1,0,1,1,0,0,1,0,1,0],
    "Embarked": ["C","S","S","S","S","Q","C","S","C","Q"],
    "FamilySize": [2,2,1,2,1,3,2,1,3,1]
}

df = pd.DataFrame(data)
df

  Name Sex  Pclass  Age  Fare  Survived Embarked  FamilySize
0    A   F       1   38    71         1        C           2
1    B   M       3   22     7         0        S           2
2    C   F       3   26     8         1        S           1
3    D   F       1   35    53         1        S           2
4    E   M       3   35     8         0        S           1
5    F   M       2   28    13         0        Q           3
6    G   F       2   19    26         1        C           2
7    H   M       3   40     7         0        S           1
8    I   F       1   30    80         1        C           3
9    J   M       2   25    15         0        Q           1

In [7]:
group = df.groupby('Sex')
group['Survived'].mean()

Sex
F    1.0
M    0.0
Name: Survived, dtype: float64

df.groupby('Pclass')['Fare'].mean()

In [8]:
df.groupby('Pclass')['Fare'].mean()

Pclass
1    68.0
2    18.0
3     7.5
Name: Fare, dtype: float64

In [11]:
df.groupby('Pclass')['FamilySize'].count()

Pclass
1    3
2    3
3    4
Name: FamilySize, dtype: int64

In [12]:
df.groupby(['Pclass', 'Sex'])['Survived'].mean()

Pclass  Sex
1       F      1.0
2       F      1.0
        M      0.0
3       F      1.0
        M      0.0
Name: Survived, dtype: float64

In [13]:
df.groupby('Pclass')['Age'].median()

Pclass
1    35.0
2    25.0
3    30.5
Name: Age, dtype: float64

In [14]:
df.groupby(['Pclass', 'Sex'])['Fare'].mean()

Pclass  Sex
1       F      68.000000
2       F      26.000000
        M      14.000000
3       F       8.000000
        M       7.333333
Name: Fare, dtype: float64

In [21]:
df['avgFare'] = df.groupby('Pclass')['Fare'].transform('mean')
df.head()

  Name Sex  Pclass  Age  Fare  Survived Embarked  FamilySize  avgFare
0    A   F       1   38    71         1        C           2     68.0
1    B   M       3   22     7         0        S           2      7.5
2    C   F       3   26     8         1        S           1      7.5
3    D   F       1   35    53         1        S           2     68.0
4    E   M       3   35     8         0        S           1      7.5

In [22]:
df['SRate'] = df.groupby('Pclass')['Survived'].transform('mean')
df.head()

  Name Sex  Pclass  Age  Fare  Survived Embarked  FamilySize  avgFare  SRate
0    A   F       1   38    71         1        C           2     68.0   1.00
1    B   M       3   22     7         0        S           2      7.5   0.25
2    C   F       3   26     8         1        S           1      7.5   0.25
3    D   F       1   35    53         1        S           2     68.0   1.00
4    E   M       3   35     8         0        S           1      7.5   0.25

In [24]:
df.groupby(['Pclass', 'Sex'])['Survived'].transform('mean')

0    1.0
1    0.0
2    1.0
3    1.0
4    0.0
5    0.0
6    1.0
7    0.0
8    1.0
9    0.0
Name: Survived, dtype: float64

In [25]:
df['FareDiff'] = df['Fare'] - df.groupby(['Pclass'])['Fare'].transform('mean')
df.head()

,Name,Sex,Pclass,Age,Fare,Survived,Embarked,FamilySize,avgFare,SRate,FareDiff
0,A,F,1,38,71,1,C,2,68.0,1.00,3.0
1,B,M,3,22,7,0,S,2,7.5,0.25,-0.5
2,C,F,3,26,8,1,S,1,7.5,0.25,0.5
3,D,F,1,35,53,1,S,2,68.0,1.00,-15.0
4,E,M,3,35,8,0,S,1,7.5,0.25,0.5

In [26]:
df.groupby(['Pclass'])['Fare'].rank(ascending = False)

0    2.0
1    3.5
2    1.5
3    3.0
4    1.5
5    3.0
6    1.0
7    3.5
8    1.0
9    2.0
Name: Fare, dtype: float64

In [30]:
df.groupby(['Pclass'])['Survived'].filter(lambda x: x.mean() > .5)

0    1
3    1
8    1
Name: Survived, dtype: int64

In [32]:
df.columns

Index(['Name', 'Sex', 'Pclass', 'Age', 'Fare', 'Survived', 'Embarked',
       'FamilySize', 'avgFare', 'SRate', 'FareDiff'],
      dtype='object')

In [33]:
df.groupby(['Pclass'])['FamilySize'].filter(lambda x: len(x) > 2)

0    2
1    2
2    1
3    2
4    1
5    3
6    2
7    1
8    3
9    1
Name: FamilySize, dtype: int64

In [34]:
df.groupby(['Pclass']).agg({
    'Survived': 'mean',
    'Fare': 'mean', 
    'Age': 'max'
})

        Survived  Fare  Age
Pclass
1       1.000000  68.0   38
2       0.333333  18.0   28
3       0.250000   7.5   40

In [44]:
df.groupby('Pclass').apply(lambda x: x.sort_values(by='Fare', ascending=False))

/tmp/ipykernel_55/3746163020.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Pclass').apply(lambda x: x.sort_values(by='Fare', ascending=False))

         Name Sex  Pclass  Age  Fare  Survived Embarked  FamilySize  avgFare  \
Pclass
1      8    I   F       1   30    80         1        C           3     68.0
       0    A   F       1   38    71         1        C           2     68.0
       3    D   F       1   35    53         1        S           2     68.0
2      6    G   F       2   19    26         1        C           2     18.0
       9    J   M       2   25    15         0        Q           1     18.0
       5    F   M       2   28    13         0        Q           3     18.0
3      2    C   F       3   26     8         1        S           1      7.5
       4    E   M       3   35     8         0        S           1      7.5
       1    B   M       3   22     7         0        S           2      7.5
       7    H   M       3   40     7         0        S           1      7.5

             SRate  FareDiff
Pclass
1      8  1.000000      12.0
       0  1.000000       3.0
       3  1.000000     -15.0
2      6  0.333333       8.0
       9  0.333333      -3.0
       5  0.333333      -5.0
3      2  0.250000       0.5
       4  0.250000       0.5
       1  0.250000      -0.5
       7  0.250000      -0.5

In [48]:
'''LEVEL 7 (REAL DATA SCIENCE THINKING)
Q16. Create:

👉 "Group_survival"

Where:

group = (Sex + Pclass)'''

df['Group_survival'] = df.groupby(['Pclass', 'Sex'])['Survived'].transform('mean')
df.head()

,Name,Sex,Pclass,Age,Fare,Survived,Embarked,FamilySize,avgFare,SRate,FareDiff,Group_survival
0,A,F,1,38,71,1,C,2,68.0,1.00,3.0,1.0
1,B,M,3,22,7,0,S,2,7.5,0.25,-0.5,0.0
2,C,F,3,26,8,1,S,1,7.5,0.25,0.5,1.0
3,D,F,1,35,53,1,S,2,68.0,1.00,-15.0,1.0
4,E,M,3,35,8,0,S,1,7.5,0.25,0.5,0.0

In [53]:
df.groupby(['Sex', 'Pclass'])['Survived'].mean().sort_values(ascending=False)

Sex  Pclass
F    1         1.0
     2         1.0
     3         1.0
M    2         0.0
     3         0.0
Name: Survived, dtype: float64

In [54]:
df.groupby(['Pclass'])['Fare'].std().sort_values(ascending = False)

Pclass
1    13.747727
2     7.000000
3     0.577350
Name: Fare, dtype: float64

In [58]:
df['Family_survival_rate'] = df.groupby(['Sex', 'FamilySize'])['Survived'].transform('mean')
df.sample(4, replace = True)

,Name,Sex,Pclass,Age,Fare,Survived,Embarked,FamilySize,avgFare,SRate,FareDiff,Group_survival,Family_survival_rate
3,D,F,1,35,53,1,S,2,68.0,1.00,-15.0,1.0,1.0
8,I,F,1,30,80,1,C,3,68.0,1.00,12.0,1.0,1.0
7,H,M,3,40,7,0,S,1,7.5,0.25,-0.5,0.0,0.0
4,E,M,3,35,8,0,S,1,7.5,0.25,0.5,0.0,0.0

In [62]:
'''Q20. Create:

👉 IsAlone (0/1) → compare survival rate'''
df['isAlone'] = (df['FamilySize'] == 1).astype(int)
df.groupby('isAlone')['Survived'].mean()

isAlone
0    0.666667
1    0.250000
Name: Survived, dtype: float64